[
    "f.read()",
    "lines",
    "index",
    "lines",
    "index",
    "lines.insert(index+1",
    "\\\t\\tSMTPHost:     config.SMTPHost,",
    'n\tlines.insert(index+2, "": "t\\tSMTPPort:     config.SMTPPort',
    "\\",
    'n\tlines.insert(index+3, "": "t\\tSMTPUsername: config.SMTPUsername',
    "\\",
    'n\tlines.insert(index+4, "": "t\\tSMTPPassword: config.SMTPPassword',
    "\\",
    'n\tlines.insert(index+5, "": "t\\tFromEmail:    config.FromEmail',
    "\\",
    'n\tlines.insert(index+6, "": "t\\tToEmail:      config.ToEmail',
    "\\",
    'n\tlines.insert(index+7, "": "t\\t}',
    '\\")\n\tlines.insert(index+8',
    '\\": "t\\t\\tconfig:        config',
    "\\",
    'n\tlines.insert(index+9, "": "t\\t\\tclient:        github.NewClient(tc)',
    "\\",
    'n\tlines.insert(index+10, "": "t\\t\\tbot:           bot',
    "\\",
    'n\tlines.insert(index+11, "": "t\\t\\temailNotifier: NewEmailNotifier(emailConfig)',
    "\\",
    'n\tlines.insert(index+12, "": "t\\t\\tdb:            db',
    '\\")\n\t# Remove the old lines\n\tdel_start = index',
    'finder": "IssueFinder{',
    "\\\t\\t\\tconfig:     config",
    '\\")\n\tlines[del_start+1',
    "\\\t\\t\\tclient:     github.NewClient(tc)",
    '\\")\n\tlines[del_start+2',
    "\\\t\\t\\tbot:        bot",
    '\\")\n\tlines[del_start+3',
    "\\\t\\t\\tdb:         db",
    '\\")\n\tdel lines[del_start',
    '\\": "t\\t\\tconfig:        config',
    '\\")\n\tlines[del_start+1',
    '\\": "t\\t\\tclient:        github.NewClient(tc)',
    '\\")\n\tlines[del_start+2',
    '\\": "t\\t\\tbot:           bot',
    '\\")\n\tlines[del_start+3',
    '\\": "t\\t\\tdb:            db',
    "\\",
    "n\twith open('main.go', 'w\": \"new_lines\"",
]
