[
    "",
    {
        "fmt.Errorf(": "ailed to connect to database: %w",
        '\\tbot, err := tgbotapi.NewBotAPI(config.TelegramBotToken)\n\tif err != nil {\n\t\tlog.Printf("Warning: Failed to connect to Telegram API: %v", err)\n\t\tbot = nil\n\t}\'\n)\n\n# 5. Add email config and emailNotifier creation after bot initialization\ncontent = content.replace(': "tdb",
        "err": "sqlx.Connect(",
        "err)\n\t}\n\n\tfinder": "IssueFinder{'",
        '\\tdb, err := sqlx.Connect("postgres", config.DBConnectionString)\n\tif err != nil {\n\t\treturn nil, fmt.Errorf("failed to connect to database: %w", err)\n\t}\n\n\temailConfig := &EmailConfig{\n\t\tSMTPHost:     config.SMTPHost,\n\t\tSMTPPort:     config.SMTPPort,\n\t\tSMTPUsername: config.SMTPUsername,\n\t\tSMTPPassword: config.SMTPPassword,\n\t\tFromEmail:    config.FromEmail,\n\t\tToEmail:      config.ToEmail,\n\t}\n\n\tfinder := &IssueFinder{\'\n)\n\n# 6. Update finder initialization to include emailNotifier\ncontent = content.replace(': "t\tconfig:     config",
        "n\t\tclient": "github.NewClient(tc)",
        "n\t\tbot": "bot",
        "n\t\tdb": "db",
        ",": "t\tconfig:        config",
        "n\t\temailNotifier": "NewEmailNotifier(emailConfig)",
        "\n)\n\n# 7. Add getEnv helper function after truncateString function\ncontent = content.replace(": "unc truncateString(s string",
        "s[": "maxLen] +",
        "',\n    'func getEnv(key, default string) string {\n\tval := os.Getenv(key)\n\tif val == \"": "n\t\treturn default",
    },
    {
        "s[": "maxLen] +",
        "'\n)\n\n# 8. Add godotenv.Load() at beginning of main function\ncontent = content.replace(\n    'func main() {\n\tconfig := &Config{',\n    'func main() {\n\tif err := godotenv.Load(); err != nil {\n\t\tlog.Printf(": "arning: Error loading .env file: %v",
        "err)\n\t}\n\n\tconfig": "Config{'\n)\n\n# 9. Update config initialization to use env vars\ncontent = content.replace(\n    '\t\tGitHubToken:        os.Getenv(",
        "GITHUB_TOKEN": "n\t\tTelegramBotToken:   os.Getenv(",
        "TELEGRAM_BOT_TOKEN": "n\t\tTelegramChatID:     683539779",
        "n\t\tCheckInterval": 3600,
        "n\t\tMaxIssuesPerRepo": 10,
        "n\t\tDBConnectionString": "getEnv(",
        ",": "t\tGitHubToken:        os.Getenv(",
        "host=localhost user=postgres password=postgres dbname=issue_finder sslmode=disable port=5432": "n\t\tSMTPHost:           os.Getenv(",
        "SMTP_HOST": "n\t\tSMTPPort:           os.Getenv(",
        "SMTP_PORT": "n\t\tSMTPUsername:       os.Getenv(",
        "SMTP_USERNAME": "n\t\tSMTPPassword:       os.Getenv(",
        "SMTP_PASSWORD": "n\t\tFromEmail:          os.Getenv(",
        "FROM_EMAIL": "n\t\tToEmail:            os.Getenv(",
        '\\tif config.GitHubToken == "" {\n\t\tlog.Fatal("GITHUB_TOKEN environment variable is required")\n\t}\n\n\tif config.TelegramBotToken == "" {\n\t\tlog.Fatal("TELEGRAM_BOT_TOKEN environment variable is required")\n\t}\',': "tif config.GitHubToken ==",
        "required": "n",
    },
    {"n\t\tlog.Printf(": "arning: TELEGRAM_BOT_TOKEN not set", "disabled": "n"},
    {"n\t\tlog.Printf(": "arning: TO_EMAIL not set", "disabled": "n"},
    [],
    {",": "treturn nil"},
    [],
    {"alert": "n\t\treturn nil"},
    [],
    {
        "\n)\n\n# 12. Add SendEmailAlert call in main loop after SendTelegramAlert\ncontent = content.replace(": "t\t\t\tif err := finder.SendTelegramAlert(issues); err != nil {\n\t\t\t\t\tlog.Printf(",
        "alert": "v",
        "issues": "len(issues))",
    },
    {
        "n\t\t\t\t\tlog.Printf(": "rror sending Telegram alert: %v",
        "issues": "len(issues))",
    },
    {
        "n\t\t\t\t\tlog.Printf(": "rror sending email alert: %v",
        "issues": "len(issues))",
    },
    {
        '\\t\t\t\t\tlog.Printf("Successfully sent email alert for %d issues", len(issues))\n\t\t\t\t}\n\t\t\t\tPrintIssuesToConsole(issues)\n\t\t\t} else {\n\t\t\t\tlog.Println("No new issues found")\'\n)\n\n# 14. Limit projects to 5 for testing\ncontent = content.replace(': "tfor _",
        "project": "range f.projects {'",
        "\\tfor i, project := range f.projects {\n\t\tif i >= 5 {\n\t\t\tbreak\n\t\t}'\n)\n\nwith open('main.go', 'w": "as f:\n    f.write(content)\n\nprint(",
        "main.go": "",
    },
]
