[
    'fmt.Errorf(": "ailed to create Telegram bot: %w',
    'log.Printf(": "arning: Failed to connect to Telegram API: %v',
    'emailConfig": "EmailConfig{\n\t\tSMTPHost:     config.SMTPHost',
    'SMTPPort": "config.SMTPPort',
    'SMTPUsername": "config.SMTPUsername',
    'SMTPPassword": "config.SMTPPassword',
    'FromEmail": "config.FromEmail',
    'ToEmail": "config.ToEmail',
    'finder": "IssueFinder{\n\t\tconfig:        config',
    'emailNotifier": "NewEmailNotifier(emailConfig)',
    'func main()": "if err := godotenv.Load(); err != nil {\n\t\tlog.Printf(',
    'warning": "Error loading .env file: %v',
    'config": "Config{\n\t\tGitHubToken:        os.Getenv(',
    'GITHUB_TOKEN": "TelegramBotToken:   os.Getenv(',
    'TELEGRAM_BOT_TOKEN":',
    -1576,
    7,
    ', "CheckInterval',
    3600,
    "MaxIssuesPerRepo",
    10,
    'SMTPHost": "os.Getenv(',
    'SMTP_HOST": "SMTPPort: "os.Getenv(',
    'SMTP_PORT": "SMTPUsername: "os.Getenv(',
    'SMTP_USERNAME": "SMTPPassword: "os.Getenv(',
    'SMTP_PASSWORD": "FromEmail: "os.Getenv(',
    'FROM_EMAIL": "ToEmail: "os.Getenv(',
    'TO_EMAIL": "alert": "if err := finder.SendEmailAlert(issues); err != nil {\n\t\t\t\t\t\tlog.Printf(',
    'alert": "v',
    'issues": "len(issues))',
]
