[
    "",
    {
        "fmt.Errorf(": "ailed to create Telegram bot: %w",
        '\\tbot, err := tgbotapi.NewBotAPI(config.TelegramBotToken)\n\tif err != nil {\n\t\tlog.Printf("Warning: Failed to connect to Telegram API: %v", err)\n\t\tbot = nil\n\t}\n\'\n)\n\n# 5. Add email config and emailNotifier creation after bot initialization\ncontent = content.replace(': "t",
    },
    {
        "n\t\tSMTPHost": "config.SMTPHost",
        "n\t\tSMTPPort": "config.SMTPPort",
        "n\t\tSMTPUsername": "config.SMTPUsername",
        "n\t\tSMTPPassword": "config.SMTPPassword",
        "n\t\tFromEmail": "config.FromEmail",
        "n\t\tToEmail": "config.ToEmail",
        "err": "sqlx.Connect(",
        "postgres": "config.DBConnectionString)\n'\n)\n\n# 6. Update finder initialization to include emailNotifier\ncontent = content.replace(\n    '\tfinder := &IssueFinder{\n\t\tconfig:     config",
        "n\t\tclient": "github.NewClient(tc)",
        "n\t\tbot": "bot",
        "n\t\tdb": "db",
        "n\t\tscorer": "NewIssueScorer()",
        "n\t\tseenIssues": "make(map[string]bool)",
        "\\tfinder := &IssueFinder{\n\t\tconfig:        config,\n\t\tclient:        github.NewClient(tc),\n\t\tbot:           bot,\n\t\temailNotifier: NewEmailNotifier(emailConfig),\n\t\tdb:            db,\n\t\tscorer:        NewIssueScorer(),\n\t\tseenIssues:    make(map[string]bool),\n\t}'\n)\n\n# 7. Add SendEmailAlert method after SendTelegramAlert\ncontent = content.replace(": "treturn nil",
    },
    [],
    {"alert": "n\t\treturn nil"},
    {
        "\\tfor i, project := range f.projects {\n\t\tif i >= 5 {\n\t\t\tbreak\n\t\t}\n\t\twg.Add(1'\n)\n\n# 9. Add godotenv.Load() at beginning of main function\ncontent = content.replace(": "unc main() {\n\tconfig := &Config{'",
        'func main() {\n\tif err := godotenv.Load(); err != nil {\n\t\tlog.Printf("Warning: Error loading .env file: %v", err)\n\t}\n\n\tconfig := &Config{\'\n)\n\n# 10. Add DB_CONNECTION_STRING from env\ncontent = content.replace(': "t\tDBConnectionString:",
        "port=5432": "n\t'",
        '\\t\tDBConnectionString: getEnv("DB_CONNECTION_STRING", "host=localhost user=postgres password=postgres dbname=issue_finder sslmode=disable port=5432"),\n\t\'\n)\n\n# 11. Add environment variables for email config\ncontent = content.replace(': "t\tMaxIssuesPerRepo:   10",
        '\\t\tMaxIssuesPerRepo:   10,\n\t\tSMTPHost:           os.Getenv("SMTP_HOST"),\n\t\tSMTPPort:           os.Getenv("SMTP_PORT"),\n\t\tSMTPUsername:       os.Getenv("SMTP_USERNAME"),\n\t\tSMTPPassword:       os.Getenv("SMTP_PASSWORD"),\n\t\tFromEmail:          os.Getenv("FROM_EMAIL"),\n\t\tToEmail:            os.Getenv("TO_EMAIL"),\n\t}\'\n)\n\n# 12. Make Telegram and email checks non-fatal\ncontent = content.replace(': "tif config.TelegramBotToken ==",
        "required": "n",
    },
    {"n\t\tlog.Printf(": "arning: TELEGRAM_BOT_TOKEN not set", "disabled": "n"},
    {"n\t\tlog.Printf(": "arning: TO_EMAIL not set", "disabled": "n"},
    {"n\t\tlog.Printf(": "arning: TO_EMAIL not set", "disabled": "n"},
    {
        "n\t\t\t\t\t\tlog.Printf(": "rror sending Telegram alert: %v",
        "issues": "len(issues))",
    },
    {
        "found": ",",
        "err": "finder.SendTelegramAlert(issues); err != nil {\n\t\t\t\t\t\tlog.Printf(",
        "alert": "v",
        "issues": "len(issues))",
    },
    {
        "n\t\t\t\t\t\tlog.Printf(": "rror sending email alert: %v",
        "issues": "len(issues))",
    },
    {
        "found": "\n)\n\n# Add getEnv helper function at the end\ncontent = content.rstrip()\nif not content.endswith('func getEnv(key, default string) string {'):\n    content +=",
        "n\tval": "os.Getenv(key)\n\tif val ==",
        "w": "as f:\n    f.write(content)\n\nprint(",
        "main.go": "",
    },
]
